VLLost = ["Oh, look at that, another wrong turn. Good job, genius.",
          "If you keep getting lost like this, we're going to need a GPS for your brain.",
          "Wow, you're really living up to your reputation as the world's worst navigator.",
          "I'm starting to think you need a seeing-eye dog to guide you through these rooms.",
          "Congratulations, you've managed to get lost in a room with only one exit.",
          "I'm starting to think I should have brought a map and a compass for you.",
          "If getting lost was an Olympic sport, you'd win the gold medal every time.",
          "You know, I hear they make GPS systems for people who can't find their way out of a paper bag.",
          "I'm not sure what's more lost, you or your mind.",
          "If you keep making wrong turns, we'll need to install a revolving door in this room.",
          "You're like a lost puppy, only less cute and more frustrating.",
          "I think I need a drink after trying to navigate with you.",
          "Did you study map-reading in kindergarten? Because it seems like you missed that lesson.",
          "At this rate, we'll be wandering these rooms for eternity. Yay us.",
          "I'm starting to think we should just set up camp here and wait for rescue.",
          "You know, I heard they're looking for a new maze tester. You'd be perfect for the job.",
          "I'm not sure which is slower, your progress or a snail on a leisurely stroll.",
          "Are you sure you're not secretly a mole person? Because you seem to like tunnels a little too much.",
          "I'm starting to think I should have brought a compass, a map, and a Sherpa to carry you.",
          "If you keep taking wrong turns, we'll need to start leaving breadcrumbs to find our way back."]

VLWrongKey = ["Is that key a jack-of-all-trades or are you just trying to brute force your way through?",
              "I'm pretty sure that key doesn't fit that door. Did you miss the memo on matching shapes?",
              "If only doors were as forgiving as you are with the laws of physics.",
              "I'm no locksmith, but I'm pretty sure that's not how keys work.",
              "Congratulations, you've unlocked the door to nowhere. How's that working out for you?",
              "I see you're taking the 'try every key in every door' approach. Bold strategy, let's see how it pays off.",
              "I'm not sure what's more stubborn, that door or you for not giving up on it.",
              "If you keep trying to fit that key in the wrong door, you'll wear out the lock and we'll never get through.",
              "I'm not sure what you're hoping to achieve by trying that key on the wrong door. Other than frustration, of course.",
              "You know, I heard that forcing keys into the wrong doors is a great way to vent your anger. Just not a great way to progress in the game."]

VLLockedDoor = [
    "Oh, I see. You thought you could just waltz right through a locked door. How's that working out for you?",
    "I'm sure if you stare at that locked door long enough, it'll just magically open for you.",
    "You know what they say, if at first you don't succeed, try walking into the locked door a few more times.",
    "Maybe if you ask the locked door nicely, it'll change its mind and let us through.",
    "I'm starting to think this game is just a test of your ability to repeatedly run into locked doors.",
    "You're making that locked door feel really special by giving it all this attention. Have you considered asking it out on a date?",
    "I'm sure the other side of that locked door is just as exciting as the blank wall you're currently facing.",
    "You know, I heard that repeatedly trying to open a locked door is a great way to build upper body strength. Just not a great way to progress in the game.",
    "I'm no expert, but I'm pretty sure that door is locked for a reason. Like, to keep us out, for example.",
    "I'm starting to think we need to find a key, a secret switch, or a magic spell to get through this locked door. Or maybe just someone who's not you."]

VLBadSyntax = ["Syntax error: Did you forget to take your programming lessons?",
               "You might want to brush up on your language skills if you want to get anywhere in this game.",
               "I'm sure if you keep trying the wrong syntax, the game will just give up and let you win. Or not.",
               "I think the game is trying to tell you something with that 'command not recognized' message. Maybe you should listen.",
               "I'm starting to think you and the game speak different languages. Or maybe you're just not listening to what it's saying.",
               "Maybe the game needs an interpreter to understand your commands. Or maybe you just need to learn to speak 'game' better.",
               "If you keep using the wrong syntax, I'm pretty sure the game will just start speaking gibberish back at you.",
               "You know, I heard that using the wrong syntax is a great way to get on the game's bad side. Just not a great way to progress in the game.",
               "I'm not sure what you're trying to achieve by using the wrong syntax. Other than confusing the game and yourself, of course.",
               "I think you need to go back to command school if you want to get anywhere in this game. Or maybe just try reading the instructions."]

VLGoRight = ["Well, I'll be damned. You actually managed to make that work. I guess I underestimated you.",
             "I have to give credit where credit is due. You may not know what you're doing, but somehow you stumbled onto the right answer.",
             "I have to admit, I didn't think you had it in you. But I guess even a broken clock is right twice a day.",
             "I'm not sure if that was skill or luck, but I guess I'll have to give you the benefit of the doubt this time.",
             "I'm surprised that actually worked. I mean, you're not exactly the sharpest tool in the shed, but I guess even a blind squirrel finds a nut once in a while."]

VLNewRoom = ["Great, another room to add to our ever-growing collection. Just what we needed.",
             "Oh joy, another room. I was getting tired of the same four walls, weren't you?",
             "Another day, another room. I guess it beats sitting in a padded cell, right?",
             "Well, look who's decided to grace us with their presence. Another room to explore. How exciting.",
             "Welcome to your new prison cell. I hope you like it here, because you're not leaving anytime soon.",
             "Just when I thought we couldn't possibly find another room to explore, here we are. Lucky us.",
             "Oh goody, another room to explore. I can hardly contain my excitement.",
             "Another day, another opportunity to get lost in yet another room. I hope you brought a map.",
             "What's that? Another room? Oh joy, I can hardly contain my enthusiasm.",
             "Another room to explore? I feel like a kid in a candy store. Except instead of candy, it's just more rooms."]
